apiVersion: v1
kind: Service
metadata:
  labels:
    app: plant-management-front-service
  name: front
spec:
  ports:
  - port: 80
  selector:
    service: plant-management-front
  type: LoadBalancer

